## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=30G
#$ -N run_crm_assoc
#$ -o stdout_run_crm_assoc
#$ -e stderr_run_crm_assoc
#$ -t 1-22

# Activate CellRegMap python environment
conda activate cellregmap_notebook

cd $SGE_O_WORKDIR

py_script=$SGE_O_WORKDIR/run_association_CD4pos_Tcells_one_gene.py

chrom=${SGE_TASK_ID}

for ((i=0; i <= 10; i++)); do
    python $py_script $chrom $i 
done
